#pragma once
#include "esp_system.h"
#include "esp_err.h"
#include "esp_log.h"
#include "driver/gpio.h"

//======================================================
#if CONFIG_IDF_TARGET_ESP32S3
// DevBoard Rev.E
//-- TASK_CORE --//
#define TASK_CORE tskNO_AFFINITY
//-- CONFIG_SOFTWARE_INTERNAL_BUTTON_SUPPORT --//
#define BUTTON_INT1_GPIO_PIN GPIO_NUM_0
//-- CONFIG_SOFTWARE_EXTERNAL_BUTTON_SUPPORT --//
#define BUTTON_EXT1_GPIO_PIN GPIO_NUM_4
//-- CONFIG_SOFTWARE_EXTERNAL_LED_SUPPORT --//
#define LED_EXT1_GPIO_PIN GPIO_NUM_21
//-- CONFIG_SOFTWARE_EXTERNAL_SK6812_SUPPORT --//
#define RGBLED_EXT1_GPIO_PIN GPIO_NUM_8
//-- CONFIG_SOFTWARE_EXTERNAL_6DIGIT_DISPLAY_SUPPORT --//
#define XDIGIT_DISPLAY_CLK_EXT1_GPIO_PIN GPIO_NUM_17
#define XDIGIT_DISPLAY_DATA_EXT1_GPIO_PIN GPIO_NUM_18
#define XDIGIT_DISPLAY_DIGIT_COUNT (6)
//-- I2C-0 --//
#define I2C0_MASTER_PORT I2C_NUM_0
#define I2C0_MASTER_SCL_PIN GPIO_NUM_4
#define I2C0_MASTER_SDA_PIN GPIO_NUM_5
#define I2C0_MASTER_STANDARD_BAUD (400000)
#define I2C0_MASTER_TIMEOUT_VALUE_MS (100)
//-- CONFIG_SOFTWARE_EXTERNAL_RTC_SUPPORT --//
#define PCF8563__CLOCK_PIN GPIO_NUM_6
#define PCF8563__INT_PIN GPIO_NUM_7
//-- UART-1 --//
#define UART1_PORT UART_NUM_1
#define UART1_RXD_PIN GPIO_NUM_17
#define UART1_TXD_PIN GPIO_NUM_18
#define UART1_RATE_BAUD (9600)
//-- CONFIG_MEASURE_OPERATION_VOLTAGE_SUPPORT --//
#define MEASURE_OPERATION_VOLTAGE_UNIT          ADC_UNIT_1
#define MEASURE_OPERATION_VOLTAGE_CHANNEL       ADC_CHANNEL_8 // GPIO_NUM_9
#define MEASURE_OPERATION_VOLTAGE_ADC_ATTEN     ADC_ATTEN_DB_6
#define MEASURE_OPERATION_VOLTAGE_RESISTOR1     (267000.0) //267K
#define MEASURE_OPERATION_VOLTAGE_RESISTOR2     (100000.0) //100K
//===========
#elif CONFIG_IDF_TARGET_ESP32C6
// DevBoard Rev.E
//-- TASK_CORE --//
#define TASK_CORE tskNO_AFFINITY
//-- CONFIG_SOFTWARE_INTERNAL_BUTTON_SUPPORT --//
#define BUTTON_INT1_GPIO_PIN GPIO_NUM_9
//-- CONFIG_SOFTWARE_EXTERNAL_BUTTON_SUPPORT --//
#define BUTTON_EXT1_GPIO_PIN GPIO_NUM_7
//-- CONFIG_SOFTWARE_EXTERNAL_LED_SUPPORT --//
#define LED_EXT1_GPIO_PIN GPIO_NUM_22
//-- CONFIG_SOFTWARE_EXTERNAL_SK6812_SUPPORT --//
#define RGBLED_EXT1_GPIO_PIN GPIO_NUM_23
//-- CONFIG_SOFTWARE_EXTERNAL_6DIGIT_DISPLAY_SUPPORT --//
#define XDIGIT_DISPLAY_CLK_EXT1_GPIO_PIN GPIO_NUM_18
#define XDIGIT_DISPLAY_DATA_EXT1_GPIO_PIN GPIO_NUM_19
#define XDIGIT_DISPLAY_DIGIT_COUNT (6)
//-- I2C-0 --//
#define I2C0_MASTER_PORT I2C_NUM_0
#define I2C0_MASTER_SCL_PIN GPIO_NUM_0
#define I2C0_MASTER_SDA_PIN GPIO_NUM_1
#define I2C0_MASTER_STANDARD_BAUD (400000)
#define I2C0_MASTER_TIMEOUT_VALUE_MS (100)
//-- CONFIG_SOFTWARE_EXTERNAL_RTC_SUPPORT --//
#define PCF8563__CLOCK_PIN GPIO_NUM_2
#define PCF8563__INT_PIN GPIO_NUM_3
//-- UART-1 --//
#define UART1_PORT UART_NUM_1
#define UART1_RXD_PIN GPIO_NUM_22
#define UART1_TXD_PIN GPIO_NUM_23
#define UART1_RATE_BAUD (9600)
//-- CONFIG_MEASURE_OPERATION_VOLTAGE_SUPPORT --//
#define MEASURE_OPERATION_VOLTAGE_UNIT          ADC_UNIT_1
#define MEASURE_OPERATION_VOLTAGE_CHANNEL       ADC_CHANNEL_4 // GPIO_NUM_4
#define MEASURE_OPERATION_VOLTAGE_ADC_ATTEN     ADC_ATTEN_DB_6
#define MEASURE_OPERATION_VOLTAGE_RESISTOR1     (267000.0) //267K
#define MEASURE_OPERATION_VOLTAGE_RESISTOR2     (100000.0) //100K
//===========
#elif CONFIG_IDF_TARGET_ESP32
// DevBoard Rev.E
//-- TASK_CORE --//
#define TASK_CORE tskNO_AFFINITY
//-- CONFIG_SOFTWARE_INTERNAL_BUTTON_SUPPORT --//
#define BUTTON_INT1_GPIO_PIN GPIO_NUM_0
//-- CONFIG_SOFTWARE_EXTERNAL_BUTTON_SUPPORT --//
#define BUTTON_EXT1_GPIO_PIN GPIO_NUM_32
//-- CONFIG_SOFTWARE_EXTERNAL_LED_SUPPORT --//
#define LED_EXT1_GPIO_PIN GPIO_NUM_27
//-- CONFIG_SOFTWARE_EXTERNAL_SK6812_SUPPORT --//
#define RGBLED_EXT1_GPIO_PIN GPIO_NUM_5
//-- CONFIG_SOFTWARE_EXTERNAL_6DIGIT_DISPLAY_SUPPORT --//
#define XDIGIT_DISPLAY_CLK_EXT1_GPIO_PIN GPIO_NUM_22
#define XDIGIT_DISPLAY_DATA_EXT1_GPIO_PIN GPIO_NUM_23
#define XDIGIT_DISPLAY_DIGIT_COUNT (6)
//-- I2C-0 --//
#define I2C0_MASTER_PORT I2C_NUM_0
#define I2C0_MASTER_SCL_PIN GPIO_NUM_32
#define I2C0_MASTER_SDA_PIN GPIO_NUM_33
#define I2C0_MASTER_STANDARD_BAUD (400000)
#define I2C0_MASTER_TIMEOUT_VALUE_MS (100)
//-- CONFIG_SOFTWARE_EXTERNAL_RTC_SUPPORT --//
#define PCF8563__CLOCK_PIN GPIO_NUM_25
#define PCF8563__INT_PIN GPIO_NUM_26
//-- UART-1 --//
#define UART1_PORT UART_NUM_2
#define UART1_RXD_PIN GPIO_NUM_16
#define UART1_TXD_PIN GPIO_NUM_17
#define UART1_RATE_BAUD (9600)
//-- CONFIG_MEASURE_OPERATION_VOLTAGE_SUPPORT --//
#define MEASURE_OPERATION_VOLTAGE_UNIT          ADC_UNIT_1
#define MEASURE_OPERATION_VOLTAGE_CHANNEL       ADC_CHANNEL_6 // GPIO_NUM_34(Input Only)
#define MEASURE_OPERATION_VOLTAGE_ADC_ATTEN     ADC_ATTEN_DB_2_5 // ADC_ATTEN_DB_6
#define MEASURE_OPERATION_VOLTAGE_RESISTOR1     (267000.0) //267K
#define MEASURE_OPERATION_VOLTAGE_RESISTOR2     (100000.0) //100K
//===========
#else
#error "No Match CONFIG_IDF_TARGET. Check mydevcboard.h"
#endif
//======================================================

#if CONFIG_SOFTWARE_INTERNAL_WIFI_SUPPORT
#include "wifi.h"
#endif

#if CONFIG_SOFTWARE_INTERNAL_BUTTON_SUPPORT
#include "button_internal.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_SK6812_SUPPORT
#include "sk6812.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_BUTTON_SUPPORT
#include "button_external.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_LED_SUPPORT
#include "led.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_RTC_SUPPORT
#include "pcf8563.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_SK6812_SUPPORT
#include "sk6812.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_SHT3X
#include "sht3x.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_SHT4X
#include "sht4x.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_BMP280
#include "bmp280.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_QMP6988
#include "qmp6988.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_BME680
#include "esp32_bme680.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_ADT7410
#include "adt7410.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_SCD30
#include "scd30.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_SCD40
#include "scd40.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_MHZ19C
#include "mhz19c.h"
#endif

#if CONFIG_SOFTWARE_SENSOR_BH1750
#include "bh1750.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_6DIGIT_DISPLAY_SUPPORT
#include "tm1637.h"
#endif

#if CONFIG_SOFTWARE_EXTERNAL_HT16K33_SUPPORT
#include "ht16k33.h"
#endif
